name: Sales Forecast Automation

on:
  schedule:
    - cron: '0 0 14 * *'  # 每月 1 號 00:00 UTC 執行
  workflow_dispatch:  # 手動觸發用

jobs:
  forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests xgboost gspread gspread_dataframe google-auth scikit-learn

    - name: Add Google Service Account
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > besparks-service-account.json

    - name: Run Sales Forecast
      run: |
        python sales_forecast.py
