name: Poya Sales Spider
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: '爬取模式 (daily/backfill)'
        required: true
        default: 'daily'
      backfill_date:
        description: '回填起始日期 (YYYY-MM-DD)'
        required: false
jobs:
  run-spider:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas gspread gspread-dataframe google-auth
          
      - name: Create Configuration Files
        run: |
          # 創建 config.json 文件
          echo '${{ secrets.CONFIG_JSON }}' > config.json
          # 創建 Google 憑證文件
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' | jq . > google-credentials.json
          
      - name: Run Poya Spider
        env:
          SCRAPE_MODE: ${{ github.event.inputs.mode || 'daily' }}
          BACKFILL_START_DATE: ${{ github.event.inputs.backfill_date || '' }}
          CONFIG_PATH: "./config.json"
          GOOGLE_APPLICATION_CREDENTIALS: "./google-credentials.json"
        run: python poya_sales_spider.py
